### ISSUE TITLE
Help wanted: How to convert self trained yolov5 model to an coreml model

### ISSUE THREAD

**Issue by airylinus** [DonMMK/AppIdea#1]
Hi Don:
    Sorry for this issue. I don't know how to get you via email so I create this issue. I found your work on yolov7 inference on iOS device, I'm trying for my own model. Would you kindly tell me how you convert the model? Thank you very much.

**Comment by DonMMK** [comment]
Hi Mongo,

There are multiple ways to convert the model. I would suggest looking at this page on playground to get started: https://www.createwithswift.com/using-an-object-detection-machine-learning-model-in-swift-playgrounds/

If you would like an app that convert .mlmodel to mlmodelc I have found this GitHub repo helpful to convert some of my mdoels: https://github.com/kkk669/CoreMLCompiler.swiftpm

In contrast if you are implementing the mlmodel in an app of yours and would like to dynamically compile it I would suggest looking at the apple developer docs: https://developer.apple.com/documentation/coreml/mlmodel/3931181-compilemodel


Other repos I have found helpful to test my models
https://github.com/ykitaguchi77/MLModelCamera

**Comment by airylinus** [comment]
@DonMMK Don Thank you so much! I really appreciate it.
